//! Compile-time attack and geometry tables for non-sliding pieces.
//!
//! Knight, king and pawn attacks never depend on occupancy, so they are simple
//! lookup tables generated by `const` functions. The `BETWEEN` and `LINE`
//! tables encode square geometry and drive pin detection and check resolution
//! in the move generator. Sliding-piece attacks live in [`crate::magic`].

use crate::bitboard::Bitboard;
use crate::types::Square;

#[inline]
const fn in_bounds(file: i32, rank: i32) -> bool {
    file >= 0 && file < 8 && rank >= 0 && rank < 8
}

#[inline]
const fn sign(x: i32) -> i32 {
    if x > 0 {
        1
    } else if x < 0 {
        -1
    } else {
        0
    }
}

#[inline]
const fn abs(x: i32) -> i32 {
    if x < 0 {
        -x
    } else {
        x
    }
}

/// True if the two squares share a rank, file or diagonal.
#[inline]
const fn aligned(af: i32, ar: i32, bf: i32, br: i32) -> bool {
    af == bf || ar == br || abs(af - bf) == abs(ar - br)
}

const fn knight_table() -> [Bitboard; 64] {
    let offsets = [
        (1, 2),
        (2, 1),
        (2, -1),
        (1, -2),
        (-1, -2),
        (-2, -1),
        (-2, 1),
        (-1, 2),
    ];
    let mut table = [Bitboard::EMPTY; 64];
    let mut sq = 0;
    while sq < 64 {
        let f = (sq % 8) as i32;
        let r = (sq / 8) as i32;
        let mut bb = 0u64;
        let mut i = 0;
        while i < 8 {
            let (df, dr) = offsets[i];
            let (nf, nr) = (f + df, r + dr);
            if in_bounds(nf, nr) {
                bb |= 1u64 << (nr * 8 + nf);
            }
            i += 1;
        }
        table[sq] = Bitboard(bb);
        sq += 1;
    }
    table
}

const fn king_table() -> [Bitboard; 64] {
    let offsets = [
        (1, 0),
        (1, 1),
        (0, 1),
        (-1, 1),
        (-1, 0),
        (-1, -1),
        (0, -1),
        (1, -1),
    ];
    let mut table = [Bitboard::EMPTY; 64];
    let mut sq = 0;
    while sq < 64 {
        let f = (sq % 8) as i32;
        let r = (sq / 8) as i32;
        let mut bb = 0u64;
        let mut i = 0;
        while i < 8 {
            let (df, dr) = offsets[i];
            let (nf, nr) = (f + df, r + dr);
            if in_bounds(nf, nr) {
                bb |= 1u64 << (nr * 8 + nf);
            }
            i += 1;
        }
        table[sq] = Bitboard(bb);
        sq += 1;
    }
    table
}

const fn pawn_table() -> [[Bitboard; 64]; 2] {
    let mut table = [[Bitboard::EMPTY; 64]; 2];
    let mut sq = 0;
    while sq < 64 {
        let f = (sq % 8) as i32;
        let r = (sq / 8) as i32;

        // White pawns attack diagonally toward rank 8.
        let mut white = 0u64;
        if in_bounds(f - 1, r + 1) {
            white |= 1u64 << ((r + 1) * 8 + (f - 1));
        }
        if in_bounds(f + 1, r + 1) {
            white |= 1u64 << ((r + 1) * 8 + (f + 1));
        }
        table[0][sq] = Bitboard(white);

        // Black pawns attack diagonally toward rank 1.
        let mut black = 0u64;
        if in_bounds(f - 1, r - 1) {
            black |= 1u64 << ((r - 1) * 8 + (f - 1));
        }
        if in_bounds(f + 1, r - 1) {
            black |= 1u64 << ((r - 1) * 8 + (f + 1));
        }
        table[1][sq] = Bitboard(black);

        sq += 1;
    }
    table
}

const fn between_table() -> [[Bitboard; 64]; 64] {
    let mut table = [[Bitboard::EMPTY; 64]; 64];
    let mut a = 0;
    while a < 64 {
        let af = (a % 8) as i32;
        let ar = (a / 8) as i32;
        let mut b = 0;
        while b < 64 {
            if a != b {
                let bf = (b % 8) as i32;
                let br = (b / 8) as i32;
                if aligned(af, ar, bf, br) {
                    let df = sign(bf - af);
                    let dr = sign(br - ar);
                    let mut bb = 0u64;
                    let mut f = af + df;
                    let mut r = ar + dr;
                    while !(f == bf && r == br) {
                        bb |= 1u64 << (r * 8 + f);
                        f += df;
                        r += dr;
                    }
                    table[a][b] = Bitboard(bb);
                }
            }
            b += 1;
        }
        a += 1;
    }
    table
}

const fn line_table() -> [[Bitboard; 64]; 64] {
    let mut table = [[Bitboard::EMPTY; 64]; 64];
    let mut a = 0;
    while a < 64 {
        let af = (a % 8) as i32;
        let ar = (a / 8) as i32;
        let mut b = 0;
        while b < 64 {
            if a != b {
                let bf = (b % 8) as i32;
                let br = (b / 8) as i32;
                if aligned(af, ar, bf, br) {
                    let df = sign(bf - af);
                    let dr = sign(br - ar);
                    let mut bb = 0u64;
                    // Extend in both directions to the board edges.
                    let mut f = af;
                    let mut r = ar;
                    while in_bounds(f, r) {
                        bb |= 1u64 << (r * 8 + f);
                        f -= df;
                        r -= dr;
                    }
                    let mut f = af + df;
                    let mut r = ar + dr;
                    while in_bounds(f, r) {
                        bb |= 1u64 << (r * 8 + f);
                        f += df;
                        r += dr;
                    }
                    table[a][b] = Bitboard(bb);
                }
            }
            b += 1;
        }
        a += 1;
    }
    table
}

/// `KNIGHT_ATTACKS[sq]` — squares a knight on `sq` attacks.
pub static KNIGHT_ATTACKS: [Bitboard; 64] = knight_table();

/// `KING_ATTACKS[sq]` — squares a king on `sq` attacks.
pub static KING_ATTACKS: [Bitboard; 64] = king_table();

/// `PAWN_ATTACKS[color][sq]` — squares a pawn of `color` on `sq` attacks.
pub static PAWN_ATTACKS: [[Bitboard; 64]; 2] = pawn_table();

/// `BETWEEN[a][b]` — squares strictly between `a` and `b` along their shared
/// rank, file or diagonal; empty if they are not aligned.
pub static BETWEEN: [[Bitboard; 64]; 64] = between_table();

/// `LINE[a][b]` — the full rank, file or diagonal through `a` and `b`, spanning
/// the whole board; empty if they are not aligned. Used as a pinned piece's
/// legal ray of movement.
pub static LINE: [[Bitboard; 64]; 64] = line_table();

/// Knight attacks from `sq`.
#[inline]
pub fn knight_attacks(sq: Square) -> Bitboard {
    KNIGHT_ATTACKS[sq.index()]
}

/// King attacks from `sq`.
#[inline]
pub fn king_attacks(sq: Square) -> Bitboard {
    KING_ATTACKS[sq.index()]
}

/// Pawn attacks from `sq` for a pawn of the given color.
#[inline]
pub fn pawn_attacks(color: crate::types::Color, sq: Square) -> Bitboard {
    PAWN_ATTACKS[color.index()][sq.index()]
}
